services:
  - type: web
    name: isa-impact-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py simulation_dashboard:server
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SKIP_PRECOMPUTATION
        value: true 